

set(C_COMP mpicc)
set(CC_COMP mpicxx)
if(DEFINED ENV{CRAYOS_VERSION})
	set(C_COMP cc)
	set(CC_COMP CC)
endif()

add_external_project_or_use_system(netcdf
  DEPENDS hdf5 zlib

  CMAKE_ARGS
  	-DCMAKE_C_COMPILER:FILEPATH=${C_COMP}
	-DCMAKE_CXX_COMPILER:FILEPATH=${CC_COMP}
    -DBUILD_SHARED_LIBS:BOOL=${BUILD_SHARED_LIBS}
    -DBUILD_TESTING:BOOL=FALSE
    -DBUILD_UTILITIES:BOOL=FALSE
    -DUSE_SZIP:BOOL=OFF
    -DENABLE_DAP:BOOL=OFF
    -DHDF5_DIR:FILEPATH=<INSTALL_DIR>/share/cmake
)
