
add_external_project(
  parmetis
  DEPENDS  mpi

  CMAKE_ARGS
    -DMETIS_INSTALL:BOOL=ON 
    -DCMAKE_BUILD_TYPE:STRING=Release 
    -DParMETIS_LIBRARY_TYPE:STRING=SHARED
    -DMETIS_LIBRARY_TYPE:STRING=SHARED
    -DCMAKE_C_COMPILER:FILEPATH=mpicc
    -DCMAKE_CXX_COMPILER:FILEPATH=mpicxx
)

